%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\Data\NSLS\X17B2\NaCl_37\EN___022_0001.edf
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/06/09 19:42:53

%% Initialize variables.
filename = 'D:\Data\NSLS\X17B2\NaCl_37\EN___022_0001.edf';
delimiter = ' ';
startRow = [1,5,7,11,13,17,19,23,25,29,31,35,37,41,43,47,49,53,55,59];
endRow = [3,5,9,11,15,17,21,23,27,29,33,35,39,41,45,47,51,53,57,59];

%% Format string for each line of text:
%   column1: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    dataArray{1} = [dataArray{1};dataArrayBlock{1}];
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
VarName1 = dataArray{:, 1};


%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID block dataArrayBlock dataArray ans;